export const PARLIAMENTARIAN_MANDATE_REPOSITORY = Symbol(
    'PARLIAMENTARIAN_MANDATE_REPOSITORY',
);

export const ACTIVE_PARLIAMENTARIAN_MANDATE_CHECKER = Symbol(
    'ACTIVE_PARLIAMENTARIAN_MANDATE_CHECKER',
);
