/** Rotas da API — espelham os controllers do backend NestJS. */
export const API_PATHS = {
    auth: {
        login: '/auth/login',
        me: '/auth/me',
    },
    dominios: '/dominios',
    usuarios: '/usuarios',
    guestUsers: '/guest-users',
    autoresExternos: '/identidade/autores-externos',
    normas: '/legislative/normas',
    atos: '/atos',
    relatorios: {
        atividadeCompleto: '/relatorios/atividade-legislativa/completo',
        presenca: '/relatorios/presenca',
    },
    legislative: {
        legislaturas: '/legislative/legislaturas',
        parlamentares: '/legislative/parlamentares',
        partidos: '/legislative/partidos-politicos',
        comissoes: '/legislative/comissoes',
        frentes: '/legislative/frentes-parlamentares',
        mesaDiretora: '/legislative/mesa-diretora',
        materias: '/legislative/materias',
        materiasAutoresExternos: '/legislative/materias/autores-externos',
        sessoes: '/legislative/sessoes-plenarias',
        agenda: '/legislative/agenda-legislativa',
        votacoes: '/legislative/votacoes',
    },
    materiasTramitar: (id: string) => `/legislative/materias/${id}/tramitar`,
    materiasAutores: (id: string) => `/legislative/materias/${id}/autores`,
    materiasPublicacoes: (id: string) => `/legislative/materias/${id}/publicacoes`,
    sessoesAbrir: (id: string) => `/legislative/sessoes-plenarias/${id}/abrir`,
    sessoesSuspender: (id: string) => `/legislative/sessoes-plenarias/${id}/suspender`,
    sessoesEncerrar: (id: string) => `/legislative/sessoes-plenarias/${id}/encerrar`,
    sessoesCancelar: (id: string) => `/legislative/sessoes-plenarias/${id}/cancelar`,
    sessoesQuorum: (id: string) => `/legislative/sessoes-plenarias/${id}/quorum`,
    normasSancao: (id: string) => `/legislative/normas/${id}/sancao`,
    normasVeto: (id: string) => `/legislative/normas/${id}/veto`,
    normasPromulgacao: (id: string) => `/legislative/normas/${id}/promulgacao`,
    normasPublicacao: (id: string) => `/legislative/normas/${id}/publicacao`,
    normasRevogar: (id: string) => `/legislative/normas/${id}/revogar`,
    votacoesVotos: (id: string) => `/legislative/votacoes/${id}/votos`,
    votacoesEncerrar: (id: string) => `/legislative/votacoes/${id}/encerrar`,
} as const;
