export enum GuestUserType {
    CITIZEN = 'CITIZEN',
    GUEST = 'GUEST',
    EXTERNAL_AUTHORITY = 'EXTERNAL_AUTHORITY',
    ORGANIZATION_REPRESENTATIVE = 'ORGANIZATION_REPRESENTATIVE',
    ATTORNEY = 'ATTORNEY',
    SPEAKER = 'SPEAKER',
    EXTERNAL_AUTHOR = 'EXTERNAL_AUTHOR',
}

export enum GuestUserStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    BLOCKED = 'BLOCKED',
}
