export const SESSAO_PLENARIA_REPOSITORY = Symbol('SESSAO_PLENARIA_REPOSITORY');
export const PEDIDO_PALAVRA_REPOSITORY = Symbol('PEDIDO_PALAVRA_REPOSITORY');
export const ATA_REPOSITORY = Symbol('ATA_REPOSITORY');
